# Generated by Django 3.2.9 on 2021-11-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=14)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('id_agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.especialidad')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.persona')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.region'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.medico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiCM.sucursal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apiCM.persona'),
            preserve_default=False,
        ),
    ]
