# Generated by Django 3.2.9 on 2021-11-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCM', '0002_auto_20211109_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.paciente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_termino',
            field=models.DateField(verbose_name='Fecha de Termino'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.medico'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.sucursal'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.region'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(max_length=90, verbose_name='Nombre de Comuna'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.persona'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.persona'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.agenda'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pago',
            field=models.IntegerField(verbose_name='Monto de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.comuna'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=14, verbose_name='Rut Persona'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=90, verbose_name='Nombre de Region'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCM.comuna'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Sucursal'),
        ),
    ]
